# Generated by Django 4.0.6 on 2022-09-29 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='discription',
            new_name='description',
        ),
    ]
