# Generated by Django 4.0.6 on 2022-10-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_orders_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='qty',
        ),
    ]
