# Generated by Django 4.0.6 on 2022-10-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_cart_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='expected_delivery_date',
            field=models.DateTimeField(null=True),
        ),
    ]
