# Generated by Django 4.0.6 on 2022-10-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0009_orders_expected_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
