# Generated by Django 4.0.6 on 2022-10-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0010_alter_cart_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
    ]
