# Generated by Django 4.0.6 on 2022-10-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0011_alter_cart_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('in-cart', 'in-cart'), ('order-placed', 'ordered-placed'), ('remove', 'remove')], default='in-cart', max_length=12),
        ),
    ]
