# Generated by Django 4.0.6 on 2022-09-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='category_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
